project:
  title: "ENVS 543-Fall 2023"
  output-dir: docs
  render:
    - "*.qmd"
    - "!homework/"
    - "!in-class/"

format:
  html:
    toc: true
    toc-title: Contents
    toc-location: right
    html-math-method: katex
    code-overflow: wrap
    code-block-border-left: "#31BAE9"
    citations-hover: true
    footnotes-hover: true
    link-external-icon: true
    self-contained: true
    output-dir: docs
    format-links: false
  revealjs:
    self-contained: true
    code-fold: false
    code-overflow: wrap
    output-dir: docs
    footer: "[Dyerlab](https://dyerlab.org)"
    format-links: false
  
