---
title: "Global CO2 Emissions"
author: "YOUR NAME HERE"
output: html
---

**Begin Instructions**: 

The text below has all the promots for the exam with a link to the raw data itself.  For each component, there is a point value indicated that I will use as a rubric.  In addition to those points, this will also be evaluated on the following:

- The data for this will be downloaded as a ZIP archive and will expand in a folder named `CSV-FILES`.  Put that folder in the same folder as this document and reference the raw data files in there for your analyses [5 pts].
- I want you to turn in the qmd file as a raw file.  It MUST render to html output WITHOUT errors [5 pts].
- I will examine the markdown code if there are programming issues that I need to follow up on for understanding your results. The rendered output MUST NOT have any R code, R chunks, or any other indication that the analyses are done in the creation of the document [5 pts].  
- Your writing should be appropriate for graduate-level discussion of data as if this were going into a scientific report [5 pts].
- You should remove all the text prompts from the output (e.g., the stuff in curly brackets I have inserted) as well as this block of instructions [5 pts].

**End Instructions**

{ A single paragraph here about why CO2 emissions are of interest to us. [5 pts]}

## The Data 

{ A narrative (e.g., not just a list of figures or R output) about the data, where it comes from, and what it contains.  This is a complete paragraph just like you find in a normal research paper [5 pts].  As part of this description, make a table describing the $CO_2$ data including columns for the minimum, mean, and maximum value for each of the emission variables. [10 pts]}

## Components of Emissions

{ The total emissions is composed of several types of data.  For the data from the year 2010, analyze and present to the reader the relative contributions of CO<sub>2</sub> by source for each of the G7 Countries. [5 pts]}

{ Divide the data into the G7 (e.g., Canada, France, Germany, Italy, Japan, the United Kingdom, and the United States) and non-G7 countries.  Compare emission output amongst all G7 countries to those from the rest of the world combined.  All plots must be labelled properly and have an appropriate caption.[10 pts] }

{ Perform a statistical analysis of G7 vs. non-G7 countries output by source.  Provide textual description of your analyses and present output as tables or in-text. [10 pts] }

## Temporal US Trends

{ For the G7 countries, deterime if total emissions between 1960-2010 are correlated?  Which two countries have the highest and which two have the lowest correlation? Describe these in words and input appropriate graphics and in-text statistical parameters (e.g., Pearson correlation; *df = X, t = Y, p = Z, r = W*). [15 pts] }

{ Take the total emission output from 1970-2010 for the US.  Attempt to develop a linear regression model to fit these emission responses.  Create appropriate plots of the raw data and model diagnostics.  Is this a good model?  Are the residuals of this model reasonably behaved?  Explain why or why not this may be an appropriate approach textually and with graphical—and if appropriate statistical—evidence. [15 pts]}

## Global Trends

{ Group all the countries by continent and take two time periods, 1984 and 2014. Make a graphic of total emissions by continent for each time period. [5 pts]}

{ Statistically test the hypothesis that total emissions by countries grouped within each continent (e.g. continent is the treatment but each country within it are the data) are not significantly different.  Describe the models you develop textually (with in-text statistical parameters as above) and use appropriate graphical and tabular output to make your point. [15 pts]}  

{ Compare the two models, are the differences between the continents the same in 2014 as they were in 1984?  Describe any differences you see. [5 pts]}

## Reference

Boden, T.A., G. Marland, and R.J. Andres. 2013. Global, Regional, and National Fossil-Fuel CO2 Emissions. Carbon Dioxide Information Analysis Center, Oak Ridge National Laboratory, U.S. Department of Energy, Oak Ridge, Tenn., U.S.A. [doi](https://doi.org/10.3334/CDIAC/00001_V2013).
