---
title: "ENVS 543 Environmental Data Literacy"
format: 
  html:
    output-dir: docs
editor: visual
---

```{r}
#| echo: false
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library( knitr ))
suppressPackageStartupMessages(library( kableExtra ))

```

## Student Learning Objectives

The content of this course is designed to support the following general student learning objectives (SLO):

-   **SLO 1:** Identity, manipulate, and summarize numerical, categorical, ordinal, logical, date, string, and spatial data types.\
-   **SLO 2:** Create habits and took the knowledge to support reproducible research.\
-   **SLO 3:** Create an informative and effective graphical display of various data types of suitable quality for inclusion in published manuscripts.\
-   **SLO 4:** Effectively choose appropriate statistical models based on the types of data at hand and the questions being addressed.\
-   **SLO 5:** Demonstrate a general understanding of spatial data types and the creation of both appropriate static and dynamic maps.

## Learning Components

This course is broken into the three separate sections, each of which maps onto *at least* one of the listed Student Learning Outcomes.

### Analytic Development & Data Manipulation

Learning R and basic data manipulations.

| Learning Module          | Assets                                                                                                                                                                |
|-----------------------|-------------------------------------------------|
| Welcome                  | [Slides](welcome_slides.html)                                                                                                                                         |
| Analysis Environment     | [Slides](analysis_environment_slides.html)                                                                                                                            |
| Git & GitHub             | [Slides](git_github_slides.html)                                                                                                                                      |
| Markdown                 | [Slides](markdown_slides.html), [Narrative](markdown.html)                                                                                                            |
| Data Types               | [Lecture Video](https://youtu.be/23GLGUvRGcY), [Slides](data_types_slides.html), [Narrative](data_types.html), [In-Class Activity](in-class/data_types_in-class.html) |
| Data Containers          | [Slides](data_containers_slides.html), [Narrative](data_containers.html)                                                                                              |
| Tidyverse                |                                                                                                                                                                       |
| Graphics that Don't Suck |                                                                                                                                                                       |
| Artificial Intelligence  |                                                                                                                                                                       |

### Statistical Analyses

Applying statistical models to make biological inferences.

| Learning Module             | Assets |
|-----------------------------|--------|
| Statistical Confidence      |        |
| Binomial                    |        |
| Categorical\~f(Categorical) |        |
| Continuous\~f(Categorical)  |        |
| Continuous\~f(Continuous)   |        |
| Categorical\~f(Continuous)  |        |

### GeoSpatial Analyses

Expanding data to include spatially relevent analyses.

| Learning Module           | Assets |
|---------------------------|--------|
| Points, Lines, & Polygons |        |
| Raster Data               |        |
| Spatial Analyses          |        |
| Raytracing                |        |
