---
title: "Discrete Data Homework"
author: "Your Name"
description: |
  This is the key to the homework on Discrete Data.
---

## Discrete Data

In this assignment, we'll be going back to our old friend, the Rice Rivers Center Data set. Here is the connection URL.

```{r}
library( tidyverse )
options( tidyverse.quiet = TRUE )
options(dplyr.summarise.inform = FALSE)
url <- "https://docs.google.com/spreadsheets/d/1Mk1YGH9LqjF7drJE-td1G_JkdADOU0eMlrP01WFBT8s/pub?gid=0&single=true&output=csv"
```

Discrete data is counting items. For this exercise, we will use the date of the record in the Rice data set to be our discrete variable. Actually, we will use the Month and Day of the Week for the Date so get ready for doing those *mutations*. So before we get going, load in the data and make a Day of the Week column and a Month column. There are several ways to get the data into the format we need, you may find one or more of `day()`, `matrix()`, `table()`, `wday()`, and `yday()`to helpful\...

1.  Use a contingency table to determine if temperatures in February that are below freezing are more frequent for any particular day of the week (e.g., test the hypothesis $H_O:$ *Freezing temperatures are independent of day of the week.*)

2.  Do a similar analysis for rain in the month of February. Count the days that had some amount of rain and group them by weekday. Note: the grouping should be by the whole day, if you have \>0 rain during the calendar day, then count it as a day that rained.

3.  Now expand this to also look at Month as a factor in addition to the weekday in a 2-dimensional contingency table and look at precipitation again. Are the days of the week and the month independent?
